server:
  port: 8081

spring:
  application:
    name: mybatis-plus
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/testtxc        #数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                   #数据库连接池最小维持连接数
      initial-size: 5                               #初始化连接数
      max-total: 5                                  #最大连接数
      max-wait-millis: 200                          #等待连接获取最大超时时间
logging:
  pattern:
    console: [%-5level] %d{yyyy-MM-dd HH:mm:ss} %c [%thread]
